### ISSUE TITLE
In example, 'if_else' return error as not defined

### ISSUE THREAD

**Issue by yongks** [has2k1/plydata#10]
Firstly, thanks for the great library here. Definitely close the gap for R users like me.

In the example given:
df >> define(z=if_else('x > 1', 1, 0)).  This returns error as 'if_else' is not defined... 

I had tried using ternary function but no luck:
df >> define (z = '1 if x>1 else 0')

Did I miss anything ?

**Comment by has2k1** [comment]
Check out the documentation, [if_else]
(https://plydata.readthedocs.io/en/stable/generated/plydata.expressions.if_else.html#plydata.expressions.if_else). Make sure to update to the latest version.

**Comment by blaiseli** [comment]
The example in the documentation is missing an import for `if_else`.

This issue should probably be considered a documentation issue.

**Comment by has2k1** [comment]
@blaiseli, thanks. https://github.com/has2k1/plydata/commit/d8ca85ff70eee621e96f7c74034e90fec16e8b61
