### ISSUE TITLE
plydata + tidypy - grammar of data manipulation...thoughts?

### ISSUE THREAD

**Issue by jcvall** [has2k1/plydata#11]
This package and plotnine are amazing....many thanks.  Any thoughts on adding tidyr functionality to plydata.  That would certainly give this package the grammar of data manipulation in one package for python in an R format.  BTY...There is no pidyr....just made that up.

**Comment by has2k1** [comment]
I have certainly [considered](https://github.com/tritemio/pybroom/issues/8#issue-237413894) it, the urge to go ahead has just not reached an overwhelming level.

**Comment by jcvall** [comment]
Regardless.  I love plydata and plotnine.  I use it quite a bit.  If I keep working at it, maybe I can create a library that mirrors tidyr in the style of pydata and share it.  I’m just not there yet.  But I will make it a goal of mine.

**Comment by has2k1** [comment]
I think this issue should stay open to show that it is a possible direction.

**Comment by has2k1** [comment]
Added [some](https://plydata.readthedocs.io/en/latest/api.html#tidy-verbs) key methods from tidyr and nearly all methods from the `forcats` package. Will be in the next release.
