### ISSUE TITLE
`str(x)` in define

### ISSUE THREAD

**Issue by beau-mind** [has2k1/plydata#14]
```
df = pd.DataFrame({'x': [0, 1, 2, 3, 4, 5], 't': [1, 2, 3, 4, 5, 6]})
df >> define(('z','str(x)'))
```
produces wrong output. I can do this using `df['x'].astype(str)` in Pandas, but will this be supported by Plotnine?

**Comment by has2k1** [comment]
It the correct output, although not what the user intends.

These are equivalent

```python
df >> define(('z','str(x)'))
df['z'] = str(df['x']))
```

Try

```python
df >> define(z='x.astype(str)')
```
