### ISSUE TITLE
add spread() and gather() functions?

### ISSUE THREAD

**Issue by derekpowell** [has2k1/plydata#16]
Just started playing with this package today and it looks really great. I was wondering if it would be possible to implement some functions for `spread()` and `gather()`. I took a quick shot at it and put together some functions that can be used with `call()` (borrowing some code from [this blog post](http://connor-johnson.com/2014/08/28/tidyr-and-pandas-gather-and-melt/)):

```python
def gather( df, key, value, cols ):
    id_vars = [ col for col in df.columns if col not in cols ]
    id_values = cols
    var_name = key
    value_name = value
    return pd.melt( df, id_vars, id_values, var_name, value_name )

def spread( df, index, columns, values ):
    return df.pivot(index, columns, values).reset_index(level=index).rename_axis(None,axis=1)

# minimal example
names = [ 'Wilbur', 'Petunia', 'Gregory' ]
a = [ 67, 80, 64 ]
b = [ 56, 90, 50 ]
df = pd.DataFrame({'names':names,'a':a,'b':b})

df_long = (df 
  >> call(gather, "drug", "heartrate", ["a","b"])
)

df_wide = (df_long
  >> call(spread, "names", "drug", "heartrate")
)
```

These work ok, but it would be even nicer to have these functions built-in and perhaps being able to be used directly, e.g.:

```df >> gather("drug", "heartrate",["a","b"])```

**Comment by has2k1** [comment]
tidyr has few functions and most (if not all) would not be out of place in this package. The goal [was](https://github.com/tritemio/pybroom/issues/8#issue-237413894) to get some of them in here.

**Comment by derekpowell** [comment]
Ah, I'm so used to working in the tidyverse, I hadn't even realized `gather()` and `spread()` were from tidyr and not dplyr. Well, will be very happy to see those implemented in the future as planned--I think that would officially seal plydata as the best dplyr/tidyr port. Thanks for all your work on the package

**Comment by has2k1** [comment]
Added [some](https://plydata.readthedocs.io/en/latest/api.html#tidy-verbs) key methods from tidyr. Will be in the next release.
