### ISSUE TITLE
Cannot import ply

### ISSUE THREAD

**Issue by joolius** [has2k1/plydata#17]
Hi,

I'm using the latest version of plydata yet I cannot import ply function:

from plydata import define, query, if_else, ply

![image](https://user-images.githubusercontent.com/10067941/73771428-a6510380-477e-11ea-86b6-5750012fe747.png)

Any advice?

**Comment by has2k1** [comment]
Sorry you got mixed up, `ply` is in the development version and it will be in the next release. If you want to use it then install the development version with

```
pip install git+https://github.com/has2k1/plydata.git@master
```

**Comment by joolius** [comment]
I see, thank you for the answer. what confused me is that the latest release docs already reference this function.
