### ISSUE TITLE
Release with pivot functions

### ISSUE THREAD

**Issue by talegari** [has2k1/plydata#18]
Dear Hassan,

I am pleasantly surprised to find this package `plydata` along with `plotnine`. Please continue this good work. This is pivotal in keeping my work 'tidy'.

When the next [release](https://plydata.readthedocs.io/en/latest/api.html#tidy-verbs) with pivot functions planned?

**Comment by has2k1** [comment]
> When the next release with pivot functions planned?

I hope to have it out within a week.

**Comment by has2k1** [comment]
v0.4.0 has been released.
