### ISSUE TITLE
Need to include 'IPython.sphinxext.ipython_console_highlighting' in doc/conf.py extensions list

### ISSUE THREAD

**Issue by juliangilbey** [has2k1/plydata#27]
Hi, I've been trying to build the documentation and I'm getting lots of warnings "doc/tutorials/dealing-with-nan-values.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known".  I found a solution at https://github.com/spatialaudio/nbsphinx/issues/24 - one just needs to add `'IPython.sphinxext.ipython_console_highlighting'` to the list of extensions in `doc/conf.py`.  The same goes for `plotnine`.

Best wishes, Julian

**Comment by has2k1** [comment]
As others noted in the linked issue, this should not happen and is probably an installation issue.
