### ISSUE TITLE
query function is not able to access variables. (UndefinedVariableError: name 'y' is not defined)

### ISSUE THREAD

**Issue by neo-anderson** [has2k1/plydata#5]
Hi !

Not sure if this is a technical limitation, but query function is not able to access the values of variables. define function does not have this problem.

This works.
```python
df = pd.DataFrame({'x': [1,2,3]})
df >> query('x > 2')
```
This doesn't.
```python
y = 2
df = pd.DataFrame({'x': [1,2,3]})
df >> query('x > y')
```
For now, I'm doing this instead -
```python
df >> query('x > {}'.format(y))
```

In the case of define, it works as expected.
```python
y = 2
df = pd.DataFrame({'x': [1,2,3]})
df >> define(sum = 'x + y')
```

**Comment by has2k1** [comment]
`query` is just [pandas.DataFrame.query](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.query.html). I think changing it would come as a surprise to pandas users. Plus can make use of  `numexpr` if available.  So you have to add a prefix `@` to the variables.

```python
df >> query('x > @y')
```

**Comment by neo-anderson** [comment]
This worked perfectly. Thanks!
