### ISSUE TITLE
define throws error when accessing column named 'n'

### ISSUE THREAD

**Issue by neo-anderson** [has2k1/plydata#6]
```python
from plydata import (define, rename, query)
df = pd.DataFrame({'n': [1,2,3]})
df >> define(y = 'n+1')
```
throws TypeError: unsupported operand type(s) for +: 'function' and 'int'
query function has no issues with it though.
```python
from plydata import (define, rename, query)
df = pd.DataFrame({'n': [1,2,3]})
df >> query('n>1')
```

**Comment by has2k1** [comment]
`n` is a [special function](https://plydata.readthedocs.io/en/stable/generated/plydata.utils.n.html#plydata.utils.n). To prevent surprises, it may be worth it to make an exception in cases where the dataframe has a column named `n`.
